/*
 * 	FIFO header for shared memory communication between niosII processors
 *
 *  	DATE		: 25-12-2025
 *      AUTHOR	    : Mathisha Bandara
*
*	Structure of the FIFO:
*	___________________________________________________________________________
*	| 	full	| 	empty	| 	count		|	|	|	|	|	|	|	|	|
*	| 	?	| 	?		| 	?		|	|	|	|	|	|	|	|	|
*	___________________________________________________________________________
*/

#ifndef FIFO_1_H_
#define FIFO_1_H_

/***********************************************************************
 * FIFO_1.h
 *
 * Hardware FIFO interface using Altera On-Chip FIFO
 * Compliant with Quartus II On-Chip FIFO documentation
 ***********************************************************************/

#include "system.h"
#include "altera_avalon_fifo_regs.h"
#include "altera_avalon_fifo_util.h"
#include "altera_avalon_fifo.h"
#include <stdint.h>

/* --------------------------------------------------------------------
 * FIFO base addresses
 *
 * These symbols MUST come from system.h
 * (generated by Platform Designer / Qsys)
 * ------------------------------------------------------------------*/

/* FIFO write interface (Avalon-MM write slave) */
#define FIFO_1_WRITE_BASE   SHARED_FIFO_OUT_BASE

/* FIFO read interface (Avalon-MM read slave, if used) */
#define FIFO_1_READ_BASE    SHARED_FIFO_OUT_BASE

/* FIFO control & status interface (CSR) */
#define FIFO_1_CSR_BASE     SHARED_FIFO_IN_CSR_BASE

/* FIFO interrupt number */
#define FIFO_1_IRQ          SHARED_FIFO_USE_IRQ


/* --------------------------------------------------------------------
 * FIFO threshold configuration
 *
 * Used by the FIFO status interface
 * ------------------------------------------------------------------*/
#define FIFO_1_ALMOST_EMPTY   2
#define FIFO_1_ALMOST_FULL    (SHARED_FIFO_OUT_FIFO_DEPTH - 5)


/* --------------------------------------------------------------------
 * Public API
 * ------------------------------------------------------------------*/

/**
 * @brief Initialize FIFO_1 control interface
 *
 * - Clears event register
 * - Programs almost-empty and almost-full thresholds
 * - Configures interrupt behavior
 */
int FIFO_1_Init(void);


/**
 * @brief Write one word into FIFO_1
 *
 * @param data 32-bit data to write
 * @return 0 on success, non-zero if FIFO is full
 */
int FIFO_1_Write(uint32_t data);


/**
 * @brief Read one word from FIFO_1
 *
 * @param data Pointer to store read value
 * @return 0 on success, non-zero if FIFO is empty
 */
int FIFO_1_Read(uint32_t *data);


/**
 * @brief Get current FIFO fill level
 *
 * @return Number of words currently stored in FIFO
 */
uint32_t FIFO_1_Level(void);


/**
 * @brief Get FIFO status register (FULL, EMPTY, etc.)
 *
 * @return Masked STATUS register value
 */
uint32_t FIFO_1_Status(void);


#endif /* FIFO_1_H_ */
